local parsers = {
    "query",
    "python",
    "meson",
    "c",
    "cpp",
    "c_sharp",
    "java",
    "kotlin",
    "html",
    "css",
    "javascript",
    "typescript",
    "json",
    "jsonc",
    "toml",
    "yaml",
    "markdown",
    "vim",
    "slint",
    "bash",
    "lua",
    "glsl",
    "gdscript",
    "mermaid",
    "latex",
    "rust",
    "go",
    "gomod",
    "gosum",
    "sql",
    "smali",
    "svelte",
    "proto",
    "powershell",
    "ini",
    "csv",
    "markdown_inline",
    "r",
    "rnoweb",
    "odin",
    "dockerfile",
    "pem",
    "haskell",
    "xml",
    "gitignore",
    "zig",
    "nix",
    "matlab",
    "jinja",
    "jinja_inline",
    "nu",
    "dart",
}

require("nvim-treesitter.configs").setup {
    ensure_installed = parsers,
    highlight = {
        enable = true,
        use_languagetree = true,
        additional_vim_regex_highlighting = true,
    },
    indent = { enable = true },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "<C-S-space>",
            node_incremental = "<C-S-space>",
            scope_incremental = false,
            node_decremental = "<bs>",
        },
    },
}
