local parsers = {
    "python",
    "meson",
    "c",
    "cpp",
    "c_sharp",
    "java",
    "kotlin",
    "html",
    "css",
    "javascript",
    "typescript",
    "json",
    "toml",
    "yaml",
    "markdown",
    -- "markdown_inline",
    "vim",
    "slint",
    "bash",
    "lua",
    "glsl",
    "gdscript",
    "mermaid",
    "latex",
    "rust",
    "go",
    "sql",
    "smali",
    "svelte",
    "proto",
    -- "csv",
    "powershell",
    "ini",
}

require("nvim-treesitter.configs").setup {
    ensure_installed = parsers,
    highlight = {
        enable = true,
        use_languagetree = true,
        additional_vim_regex_highlighting = true,
    },
    indent = { enable = true },
}
